version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ritchie
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pg:
    image: dpage/pgadmin4
    container_name: pg
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ritchie-invest.eu
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres-data: