-- CreateTable
CREATE TABLE "Life" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "lostAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Life_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Life" ADD CONSTRAINT "Life_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
